import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import SideNav from "./_components/SideNav";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${geist.variable} bg-background text-white`}>
			<body>
				<TRPCReactProvider>
					<div className="flex h-screen">
						<SideNav />
						<div className="flex-1">{children}</div>
					</div>
				</TRPCReactProvider>
			</body>
		</html>
	);
}
